### ISSUE TITLE
Warning: Can't resolve all parameters for GalleryService in `gallery.service.d.ts: (?)`. This will become an error in Angular v5.x

### ISSUE THREAD

**Issue by leocaseiro** [MurhafSousli/ng-gallery#21] opened 2017-06-30 02:52 UTC
> Warning: Can't resolve all parameters for GalleryService in `/node_modules/ng-gallery/service/gallery.service.d.ts: (?)`. This will become an error in Angular v5.x

Hi, if you run AOT or build -prod, you'll see this warning on `@angular@4.2.4`.

I couldn't find myself what is not resolved, but I thought openning this issue will get some more help. Thanks

**Comment by MurhafSousli** [comment] 2017-06-30 15:21
I am getting this issue on different plugins, most probably it is caused by ngc I used for building the module

**Comment by ekiras** [comment] 2017-09-04 19:46
any update on this one, i am also getting same warning on one of of my library

**Comment by MurhafSousli** [comment] 2017-09-04 20:06
@ekiras This will be fixed in the next update

**Comment by kondi** [comment] 2017-09-29 10:33
@MurhafSousli Could we have a release soon? Angular 5 has released rc0 and I would like to prepare my app for the final version.

**Comment by MurhafSousli** [comment] 2017-11-01 11:42
This is fixed now

**Closed by MurhafSousli** 2017-11-01 11:42 UTC

**Comment by mfrro** [comment] 2017-11-07 15:54
@MurhafSousli 
The fix doesn't seem to be in the current release (1.0.0-beta.8), are you planning on releasing soon? Thanks
